### ISSUE TITLE
Initial Data Scraping: Bread

### ISSUE THREAD

**Issue by godwinpang** [Honey4Groceries/Honey4Groceries#17]
Let's try to get an initial dataset of bread names to work with. 
Search Term: Bread
Store: Costco

I think a good place to start would just be to use ~~BeautifulSoup~~ Scrapy, and focus on scraping the data from the list of urls that you will get from the website. (Bread has multiple pages) Don't think about scalability yet; this is just to get you more comfortable with python and webscraping in general.

**Comment by godwinpang** [comment]
On second thought, it might be useful to start with Scrapy since it is meant for web crawling as well. 
More research to be done.

**Comment by vivianweiii** [comment]
scrapy official tutorial:
https://doc.scrapy.org/en/latest/intro/tutorial.html

**Comment by godwinpang** [comment]
Vons doesn't have robots.txt, try disabling that middleware

**Comment by vivianweiii** [comment]
This unsurprisingly turned out even more complicated than I asked for. So the issue in short is that there's something called deferred scripts that run *AFTER* the page is loaded that put the additional info in such as prices and names. Therefore scrapy does not get the info when it sends the first request. Trying to find ways to solve this problem and this is a google doc that I'm keeping my thought process on (also shared with Peter): https://docs.google.com/document/d/1h3k2N6I_9Gs2sMZpQwsHEqLRMWtRAS81AQVp4bHaKaw/edit

Happy Holidays!

**Comment by vivianweiii** [comment]
Sorry forgot to indicate that the site I was trying to scrape in the above comment was Ralphs...
Note: Vons is similarly hard to scrape due to its horrifying format and issue with scripts and infinite scrolling, so Ralphs may be better to start off with

**Comment by godwinpang** [comment]
https://docs.google.com/document/d/1h3k2N6I_9Gs2sMZpQwsHEqLRMWtRAS81AQVp4bHaKaw/edit?ts=5c1abd4e
